@startmindmap
*[#Orange] Java 复习点
    *[#lightgreen] Java 集合
        *[#yellowgreen] 线程安全
            * Map
                * CurrentHashMap
        *[#lightgreen] 非线程安全
            * Map
                * HashMap
left side
    *[#gray] JUC
        *[#lightblue] 进程、线程、协程的区别
            * 进程：是操作系统中拥有资源和独立运行的最小单位，进程之间资源不可共享；
            * 线程：是进程执行的最小单元，是处理器调度和分配的基本单位。\n线程可以共享进程内的所有资源；
            * 协程：协程不属于操作系统的概念，完全由程序执行，即在用户态执行。\n对于线程是另一种更细粒度的划分
        *[#Aqua] 创建线程的几种方式
        *[#LightCyan] 线程池
            * 线程池的核心参数
                * corePoolSize：核心线程数；
                * BlockingQueue：工作队列；
                * maximumPoolSize：最大非核心线程数；
                * keepAliveTime：非核心线程数存活时间；
                * TimeUnit：时间单位；
                * ThreadFactory：创建线程的工厂；
                * RejectedExecutionHandler：拒绝策略
                    * AbortPolicy: 直接拒绝，并抛出异常；
                    * CallerRunsPolicy：谁丢弃，谁执行
            
@endmindmap
